version: '3'

services:
  db:
    image: postgres:12
    restart: unless-stopped
    container_name: pg_db
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - shipping-db:/var/lib/postgresql/data
    networks:
      - shipping-service

  pg_admin:
    image: dpage/pgadmin4
    container_name: lb_pg_admin
    restart: unless-stopped
    ports:
      - '4500:80'
    depends_on:
      - db
    networks:
      - shipping-service
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMN_PASS}

  backend:
    image: shipping-service-backend
    container_name: shipping-service-backend
    env_file: ./env/.env
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    expose:
      - 80
    ports:
      - '4501:80'
    command: bash -c alembic upgrade head && scripts/init-data.sh && uvicorn main:app --port 80 --host 0.0.0.0 --reload
    volumes:
      - .:/app/shipping
    networks:
      - shipping-service
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.shipping-service.rule=(Host(`shipping.localhost`) && PathPrefix(`/api`))'

volumes:
  shipping-db:

networks:
  shipping-service:
