"""initial

Revision ID: ba95e3fbd36b
Revises: 
Create Date: 2022-01-06 11:22:41.793698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ba95e3fbd36b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("code", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(), nullable=True),
        sa.Column("createdat", sa.DateTime(), nullable=True),
        sa.Column("updateat", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_countries_code"), "countries", ["code"], unique=True)
    op.create_index(op.f("ix_countries_name"), "countries", ["name"], unique=True)
    op.create_table(
        "fuel_costs",
        sa.Column("uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("petrol_cost", sa.Float(), nullable=True),
        sa.Column("diesel_cost", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(), nullable=True),
        sa.Column("createdat", sa.DateTime(), nullable=True),
        sa.Column("updatedat", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "locations",
        sa.Column("uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("country_uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("createdat", sa.DateTime(), nullable=True),
        sa.Column("updatedat", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["country_uuid"], ["countries.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_locations_name"), "locations", ["name"], unique=False)
    op.create_table(
        "shipments",
        sa.Column("uuid", postgresql.UUID(), nullable=False),
        sa.Column("from_location", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("to_location", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("distance_km", sa.Float(), nullable=False),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("product_weight", sa.Float(), nullable=True),
        sa.Column("product_volume", sa.Float(), nullable=True),
        sa.Column("shipping_date", sa.Date(), nullable=False),
        sa.Column("sender_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("receiver_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "intransit",
                "delivered",
                "cancelled",
                name="shipmentstatustypes",
            ),
            nullable=False,
        ),
        sa.Column("createdat", sa.DateTime(), nullable=True),
        sa.Column("updatedat", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_location"], ["locations.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["to_location"], ["locations.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_shipments_receiver_user_id"),
        "shipments",
        ["receiver_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_shipments_sender_user_id"),
        "shipments",
        ["sender_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shipments_sender_user_id"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_receiver_user_id"), table_name="shipments")
    op.drop_table("shipments")
    op.drop_index(op.f("ix_locations_name"), table_name="locations")
    op.drop_table("locations")
    op.drop_table("fuel_costs")
    op.drop_index(op.f("ix_countries_name"), table_name="countries")
    op.drop_index(op.f("ix_countries_code"), table_name="countries")
    op.drop_table("countries")
    # ### end Alembic commands ###
